### Testes interativos de Autorização e Políticas (Capítulo 15)

### 1. Chamada sem autenticação (401)
GET http://localhost:8080/api/v1/faturas

### 2. Login de Operador (Alçada R$ 1.000)
# @name loginOperador
POST http://localhost:8080/api/v1/auth/token?perfil=operador

### 3. Tentar Cancelar Fatura de R$ 15.000 com Operador (403 Forbidden)
DELETE http://localhost:8080/api/v1/faturas/105
Authorization: Bearer {{loginOperador.response.body.token}}

### 4. Login de Diretoria (Alçada R$ 50.000)
# @name loginDiretoria
POST http://localhost:8080/api/v1/auth/token?perfil=diretoria

### 5. Cancelar Fatura Crítica com Diretoria (204 No Content)
DELETE http://localhost:8080/api/v1/faturas/105
Authorization: Bearer {{loginDiretoria.response.body.token}}
